COT_TO_CANONICAL = {
    "BITCOIN - CHICAGO MERCANTILE EXCHANGE": "Bitcoin",
    "GOLD - COMMODITY EXCHANGE INC.": "Gold",
    "ETHER CASH SETTLED - CHICAGO MERCANTILE EXCHANGE" : "Ethereum",
    "XRP - CHICAGO MERCANTILE EXCHANGE" : "XRP"
    # add others as needed
}